# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ear_process <- function(wav, inNumOfChannels, inFirstFreq, inFreqDist, inSampleFrequency) {
    .Call('_eaR_ear_process', PACKAGE = 'eaR', wav, inNumOfChannels, inFirstFreq, inFreqDist, inSampleFrequency)
}

