# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

times <- function(a) {
    .Call(`_eaR_times`, a)
}

ear_process <- function(wav, inNumOfChannels, inFirstFreq, inFreqDist, inSampleFrequency) {
    .Call(`_eaR_ear_process`, wav, inNumOfChannels, inFirstFreq, inFreqDist, inSampleFrequency)
}

